import type { Metadata } from 'next'
import Link from 'next/link'
import { ReactQueryClientProvider } from '@/components/ReactQueryClientProvider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={`flex h-screen w-screen flex-col overflow-hidden antialiased`}>
          <header className="flex w-full p-5">
            <Link href="/">Home</Link>
          </header>
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}
